name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cc: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - run: make test CC=${{ matrix.cc }}
